# Generated by Django 4.0.6 on 2022-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_port', models.CharField(default='-', max_length=100)),
                ('m_pro_class', models.CharField(default='-', max_length=100)),
                ('bussiness_class', models.CharField(default='-', max_length=100)),
                ('measure', models.CharField(default='-', max_length=100)),
                ('country_port', models.CharField(default='-', max_length=100)),
                ('meo', models.CharField(choices=[('MEO', 'MEO'), ('Non MEO', 'Non MEO'), ('Others', 'Others')], default='MEO', max_length=10)),
                ('type_fill', models.CharField(default='-', max_length=100)),
                ('vessel', models.CharField(default='-', max_length=100)),
                ('distributor', models.CharField(choices=[('End Customer Non Index', 'End Customer Non Index'), ('End Customer Index', 'End Customer Index'), ('MD', 'MD'), ('MD Distributor', 'MD Distributor')], default='MD', max_length=50)),
                ('vessel_segment', models.CharField(default='-', max_length=100)),
                ('emp_name', models.CharField(default='-', max_length=100)),
                ('cust_type', models.CharField(choices=[('International', 'International'), ('Local', 'Local')], default='Local', max_length=100)),
                ('cust_group', models.CharField(default='-', max_length=100)),
                ('cust_name_rev', models.CharField(default='-', max_length=100)),
                ('mode_delivery', models.CharField(choices=[('Barge Delivery', 'Barge Delivery'), ('Road Delivery', 'Road Delivery'), ('Not Assigned', 'Not Assigned'), ('-', '-')], default='-', max_length=100)),
                ('rtm_model', models.CharField(default='-', max_length=100)),
                ('ship_to_party', models.CharField(default='-', max_length=100)),
                ('cust_code', models.CharField(default='-', max_length=100)),
                ('period_year', models.CharField(default='-', max_length=100)),
                ('c4', models.CharField(default='-', max_length=100)),
                ('volume', models.CharField(default='-', max_length=100)),
                ('volume_buckets', models.CharField(default='-', max_length=100)),
                ('material', models.CharField(default='-', max_length=100)),
                ('imo_number', models.CharField(default='-', max_length=100)),
                ('port', models.CharField(default='-', max_length=100)),
                ('sales_org', models.CharField(default='-', max_length=100)),
                ('banding', models.CharField(default='-', max_length=100)),
                ('cust_country', models.CharField(default='-', max_length=100)),
                ('cust_code_rev', models.CharField(default='-', max_length=100)),
                ('cust_segment', models.CharField(default='-', max_length=100)),
                ('material_code', models.CharField(default='-', max_length=100)),
                ('mpo_name', models.CharField(default='-', max_length=100)),
                ('pack_from', models.CharField(default='-', max_length=100)),
                ('rsm', models.CharField(default='-', max_length=100)),
                ('ship_party', models.CharField(default='-', max_length=100)),
                ('vessel_code', models.CharField(default='-', max_length=100)),
                ('vessel_sub_type', models.CharField(default='-', max_length=100)),
                ('volume_l15', models.CharField(default='-', max_length=100)),
                ('c3_margin', models.CharField(default='-', max_length=100)),
                ('agent_comm', models.CharField(default='-', max_length=100)),
                ('c4_1', models.CharField(default='-', max_length=100)),
                ('up_cpl', models.CharField(default='-', max_length=100)),
                ('ucogs_cpl', models.CharField(default='-', max_length=100)),
                ('udcost_cpl', models.CharField(default='-', max_length=100)),
                ('ucost_cpl', models.CharField(default='-', max_length=100)),
                ('uc3_cpl', models.CharField(default='-', max_length=100)),
                ('uc4_cpl', models.CharField(default='-', max_length=100)),
                ('non_meo', models.CharField(default='-', max_length=100)),
                ('plan_volume_L15', models.CharField(default='-', max_length=100)),
                ('plan_c3_margin', models.CharField(default='-', max_length=100)),
                ('plan_agent_comm', models.CharField(default='-', max_length=100)),
                ('plan_c4_margin', models.CharField(default='-', max_length=100)),
                ('sum_of_cogs', models.CharField(default='-', max_length=100)),
                ('sum_of_d_cost', models.CharField(default='-', max_length=100)),
                ('sum_of_net_proc', models.CharField(default='-', max_length=100)),
                ('sales_org_code', models.CharField(default='-', max_length=100)),
                ('sum_of_total_cost', models.CharField(default='-', max_length=100)),
                ('sum_of_vol_var', models.CharField(default='-', max_length=100)),
                ('use', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=100)),
            ],
        ),
    ]
